### ISSUE TITLE
Incorrect variables in presets

### ISSUE THREAD

**Issue by TimPeterson** [bitfocus/companion-module-zinc-oscpoint#2]
Two of the module presets, the ones that display the slide number and build number, reference incorrect variable names when the connection name is not set to the default "OSCPoint". The total slides and total builds show as $NA.

![OSCPoint presets](https://github.com/bitfocus/companion-module-zinc-oscpoint/assets/5335557/f2e73ed8-4b29-40da-b24c-a06509a6eb18)

**Comment by phuvf** [comment]
Thanks for the issue - I'll look into this and hope to have a fix for the next release. Probably have to just build these buttons manually until then.

**Comment by phuvf** [comment]
This appears to be due to a bug in the core code of Companion - more details forthcoming soon.

**Comment by phuvf** [comment]
Think this is now fixed in the core
